spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gateway-db
    username: root
    password: admin123
    driver-class-name:
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: gateway-service
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true

server:
  port: 80
  forward-headers-strategy: FRAMEWORK
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka


