spring:
  cloud:
    gateway:
      routes:
        - id: openapi
          uri: http://localhost:8080
          predicates:
            - Path=/v3/api-docs/**-
        - id: product-service
          uri: http://localhost:8082/
          predicates:
            - Path=/api/v1/product/**
        - id: customer-service
          uri: http://localhost:8220/
          predicates:
            - Path=/api/v1/customer/**
