


#eureka.client.serviceUrl.defaultZone = http://localhost:8761/eureka/
#spring.config.import=configserver:http://localhost:8888/api/config

spring.data.mssql.host=localhost
spring.data.mssql.user=sa
spring.data.mssql.password=softweb#123
spring.data.mssql.database=sqldb-ecom-gateway
